# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180810_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150', upload_to='images/blog/%Y/%m/%d', verbose_name='link image'),
        ),
    ]
